---
title: "SAGs - Contamination"
author: "Aleix Obiol"
date: "2026-09-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../aux_functions_sags.R")

```

## Read data

```{r}
tableS1 <- 
  readxl::read_excel('../../data/sags/Table-S1.xlsx')

tableS2 <- 
  readxl::read_excel('../../data/sags/Table-S2.xlsx')

mtags_summary <- 
  readxl::read_excel('../../data/mtags/sept26_mtags_otu_table_table_clean_with_NAs.xlsx')
```
## mtags

```{r}
mtags_filtered <- 
  mtags_summary |> 
  select(
    sag_id = SAG,
    purity = `purity_relaxed (%)`,
    n_mtags = mtags
    ) |> 
  mutate(purity = as.numeric(purity)) |> 
  replace_na(list(purity= 0)) |>
  arrange(-n_mtags) |> 
  mutate(sag_id = fct_inorder(sag_id))

p_mtags_purity <- 
  mtags_filtered |> 
  ggplot(aes(x = sag_id, y  = purity)) +
  geom_col(fill = 'tan2',
           color = 'gray20',
           linewidth = 0.1) +
  theme_sags() +
  scale_y_continuous(expand = c(0,0)) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
  ) +
  labs(x = 'SAGs', y = 'Purity (%)') +
  geom_rect(xmin = 272, xmax = 326, ymin =0, ymax =100, fill = 'gray90')

p_n_mtags <- 
  mtags_filtered |> 
  ggplot(aes(x = sag_id, y  = n_mtags)) +
  geom_col(fill = alpha('tan2',.5),
           color = 'gray20',
           linewidth = 0.1) +
  theme_sags() +
  geom_rect(xmin = 272, xmax = 326, ymin =0, ymax =3.625, fill = 'gray90') +
  geom_text(check_overlap = T, aes(x = 300, label = 'No mtags retrieved', y = 100), color = 'gray40') +
  scale_y_log10(expand = c(0,0)) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
  ) +
  labs(x = NULL, y = '# mtags')

p_mtags <- 
  wrap_plots(
    p_n_mtags,
    plot_spacer(),
    p_mtags_purity,
    heights = c(.2,-.1,.8)
    )
```


## Plot contamination

```{r}
prok_removed <- 
  tableS1 |> 
  mutate(
    euk_perc = 100-`%-prokarya-size`,
    euk_mb = `Mb (≥1k)`-`Mb-prokarya`
    ) |> 
  select(sag_id = `Cell name`,
         prok_mb = `Mb-prokarya`,
         prok_perc = `%-prokarya-size`,
         euk_mb,
         euk_perc
         ) |> 
  arrange(-prok_perc) |> 
  mutate(sag_id = fct_inorder(sag_id))
  
prok_removed_perc <- 
  prok_removed |> 
  select(1, contains('perc')) |> 
  pivot_longer(-sag_id, names_pattern = '(.*)_.*') |> 
  mutate(name = if_else(name == 'prok','Prokaryotic','Eukaryotic'))

prok_removed_mb <- 
  prok_removed |> 
  select(1, contains('mb')) |> 
  pivot_longer(-sag_id, names_pattern = '(.*)_.*') |> 
  mutate(name = if_else(name == 'prok','Prokaryotic','Eukaryotic'))

p_prok_removed_all <- 
  prok_removed_perc |> 
  ggplot(aes(x = sag_id, y = value)) +
  geom_col(aes(fill = fct_rev(name)),
           color = 'gray20',
           linewidth = 0.1) +
  theme_sags() +
  scale_y_continuous(expand = c(0,0)) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.title = element_blank(),
    legend.position = 'bottom'
  ) +
  labs(y = '% of assembly', x = 'SAGs') +
  scale_fill_manual(values = c(Prokaryotic = 'maroon2', Eukaryotic = 'springgreen2'))

p_prok_removed_mb <- 
  prok_removed_mb |>
  filter(name == 'Prokaryotic') |> 
  ggplot(aes(x = sag_id, y = value)) +
  geom_col(fill = 'maroon2',
           color = 'gray20',
           linewidth = 0.1) +
  theme_sags() +
  scale_y_continuous(expand = c(0,0)) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
  ) +
  labs(y = 'Mbp', x = NULL)

p_prok_removed_summary <- 
  prok_removed_perc |> 
  ggplot(aes(x = fct_rev(name), y = value)) +
  geom_point(position = position_jitter(height = 0, width = 0.2), aes(fill = name), alpha = 0.6, shape = 21, color = 'gray20', stroke = 0.2) +
  theme_sags() +
  geom_boxplot(outlier.shape = NA, alpha = 0.2, aes(fill = name), linewidth = 0.2) +
  scale_fill_manual(values = c(Prokaryotic = 'maroon2', Eukaryotic = 'springgreen2')) +
  guides(fill = 'none') + 
  labs(x = NULL, y = '% of assembly')
  
p_prok_contamination <- 
  wrap_plots(
    wrap_plots(
     p_prok_removed_mb,
      plot_spacer(),
      p_prok_removed_all + guides(fill = 'none'),
      heights = c(.2,-.1,.8)
     ),
    p_prok_removed_summary,
    widths = c(.8,.2)
  ) + 
  plot_annotation(tag_levels = list(c('A','','B')))
  
ggsave(plot = p_prok_contamination, filename = '../../figures/supp_contamination.pdf', height = 4, width = 8)

most_contaminated <- 
  prok_removed |> 
  slice_head(n =10) |> 
  pull(sag_id)

write_lines(most_contaminated, '../../data/sags/blob_data/most_contaminated.txt')
```

## blob plots

### read and process data

```{r}
coverage_tables <- 
  most_contaminated |> 
  set_names() |> 
  map(
    ~ read_tsv(str_c('../../data/sags/blob_data/',.x,'_filter1_coverage.tsv'))
  ) |> 
  bind_rows(.id = 'sag_id') |> 
  select(sag_id, contig = `#rname`, meandepth)

removed_contigs <- 
  most_contaminated |> 
  set_names() |> 
  map(
    ~ tibble(
      contig = read_lines(str_c('../../data/sags/blob_data/',.x,'_removed_in_filter3.txt')),
      kept = 'no'
    )
  ) |> 
  bind_rows(.id = 'sag_id')

gc_tables <- 
  most_contaminated |> 
  set_names() |> 
  map(
    ~ read_tsv(str_c('../../data/sags/blob_data/',.x,'_contigs_gc_content.tsv'), col_names = c('contig', 'length', 'gc'))
  ) |> 
  bind_rows(.id = 'sag_id')  

blob_data_df <- 
  gc_tables |> 
  left_join(coverage_tables) |> 
  left_join(removed_contigs) |> 
  replace_na(list(kept = 'yes')) |> 
  mutate(sag_id = factor(sag_id, levels = most_contaminated))
```

### plots

```{r}
p_blobs <- 
  blob_data_df |> 
  ggplot(aes(x = gc, y = meandepth)) +
  geom_point(alpha = 0.5, aes(size = length, color = fct_rev(kept))) +
  facet_wrap(~ sag_id, scales = 'free') + 
  theme_sags() +
  scale_color_manual(name = 'Kept', values = c(no = 'maroon2', yes = 'springgreen2')) +
  scale_y_log10() +
  labs(x = 'GC content (%)', y = 'Mean depth of coverage')

# ggsave(plot = p_blobs, filename = '../../figures/blob_plots.pdf', height = 10, width = 15)
```

## Final figure

```{r}
p_blobs_top3 <- 
  blob_data_df |>
  filter(sag_id %in% most_contaminated[1:3]) |> 
  ggplot(aes(x = gc, y = meandepth)) +
  geom_point(alpha = 0.5, aes(size = length/1e3, color = fct_rev(kept))) +
  facet_wrap(~ sag_id, scales = 'free') + 
  theme_sags() +
  scale_color_manual(name = 'Kept', values = c(no = 'maroon2', yes = 'springgreen2')) +
  scale_y_log10() +
  labs(x = 'GC content (%)', y = 'Mean depth of coverage') +
  guides(size =guide_legend(title = 'Length (kbp)'),
         color = guide_legend(override.aes = list(size = 3)))

p_prok_contamination_no_summary <- 
  wrap_plots(
     p_prok_removed_mb,
      plot_spacer(),
      p_prok_removed_all,
      heights = c(.2,-.1,.8)
     )

fig <- "S1"

caption <-
  get_caption(fig)

figS1 <- 
  wrap_plots(p_mtags,p_prok_contamination_no_summary, free(p_blobs_top3, side = 'r'), heights = c(.3,.3,.2)) + 
  plot_annotation(tag_levels = list(c('A','','B','','C','D')))  

figS1_with_caption <- 
  figS1 +
  labs(
    caption = caption
  ) +
  theme(
    plot.caption = element_textbox_simple(
      margin = margin(5, 0, 5, 0),
      width = unit(1, "npc"),
      size = 8
    )
  )

ggsave(plot = figS1, filename = '../../figures/supp_figures/figS1.pdf', height = 10, width = 10)
ggsave(plot = figS1_with_caption, filename = '../../figures/supp_figures/with_caption/figS1_with_caption.pdf', height = 10, width = 10)
```

