---
title: "SAGs technical results - Figure ANI"
author: "Aleix Obiol"
date: "2026-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../aux_functions_sags.R")
```

## Read data

```{r}
ani_df <- 
  read_tsv('../../data/ani/ani_data.tsv.gz', col_names = c('sag_id', 'query', 'len','pident','subject'))
```

## Plot histograms

```{r}
ani_df_filtered <- 
  ani_df |> 
  mutate(query = str_match(query, '(.*)_')[,2]) |> 
  filter(query != subject)

ani_df_filtered_len <- 
  ani_df_filtered |> 
  mutate(bin_pident = cut_width(pident, width = 1, boundary = 100)) |> 
  group_by(sag_id, bin_pident) |> 
  summarise(bin_length = sum(len))

p_ani_hist <- 
  ani_df_filtered |> 
  ggplot(aes(x = pident)) +
  geom_histogram(binwidth = 1, color = 'white', linewidth = .2, boundary = 100) +
  facet_wrap(~ sag_id, scales = 'free_y', ncol = 6) +
  theme_sags() +
  theme(strip.text = element_text(size = 6)) +
  labs(y = 'Number of contigs', x = 'Percentage of identity') +
  scale_x_continuous(labels = ~ paste0(.x,'%'))

ggsave(plot = p_ani_hist, filename = '../../figures/fig_ani.pdf', height = 10, width = 14)

p_ani_hist_len <- 
  ani_df_filtered_len |> 
  ggplot(aes(x = bin_pident, y = bin_length/1e6)) +
  geom_col(color = 'white', linewidth = .2) +
  facet_wrap(~ sag_id, scales = 'free_y', ncol = 6) +
  theme_sags() +
  theme(strip.text = element_text(size = 6)) +
  labs(y = 'Size (Mbp)', x = 'Percentage of identity') +
  scale_x_discrete(
    breaks = function(x) x[as.numeric(sub(".*,", "", gsub("\\(|\\]", "", x))) %in% c(70, 80, 90, 100)],
    labels = function(x) sub(".*,", "", gsub("\\(|\\]", "%", x)),
    drop = F
  )

ggsave(plot = p_ani_hist_len, filename = '../../figures/fig_ani_len.pdf', height = 10, width = 14)
```

