---
title: "SAGs technical results - Figure ANI negative control"
author: "Aleix Obiol"
date: "2026-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../aux_functions_sags.R")
```

## Read data

```{r}
comparisons_data <- 
  read_tsv('../../data/ani/comparisons.tsv') # min 14% overlap

get_comparison <- function(filename){
  
  filename <- basename(filename)
  query = str_match(filename, 'blast_f_sc_(ICM....)')[,2]
  subject = str_match(filename, '_to_(ICM....)')[,2]
  comparison = str_c(sort(c(query, subject)),collapse = ' vs ')
  
  return(comparison)
}

ani_df <- 
  list.files('../../data/ani/',pattern = 'blast', full.names = T) |> 
  map(
    ~ read_tsv(.x,
             col_names = c('query', 'len','pident','subject')) |> 
      mutate(
        comparison = get_comparison(.x),
        group = str_match(.x, '.*_(.*?)_to_')[,2]
      )
  ) |> 
  bind_rows() |> 
  left_join(comparisons_data) |> 
  mutate(
    name = paste0(comparison, ' (',group,')<br>*18S identity between SAGs:* ',`%-18S`,'%<br>*Fraction of genome compared:* ',`%-compared genomes`,'%'),
         name = str_replace(name, '-%','-'),
         comparison = factor(comparison, levels = comparisons_data$comparison)) |> 
  arrange(comparison) |> 
  mutate(name = str_replace(name, 'ICM', '**ICM'),
         name = str_replace(name, ' vs ','** vs **'),
         name = str_replace(name, ' \\(','** ('),
         name = fct_inorder(name))
```

## Plot histograms

```{r}
p_ani_hist_same <- 
  ani_df |> 
  filter(str_detect(type, 'same')) |> 
  ggplot(aes(x = pident)) +
  geom_histogram(binwidth = 1, color = 'white', linewidth = .2, boundary = 100) +
  facet_wrap(~ name, scales = 'free_y', nrow = 1) +
  theme_sags() +
  theme(strip.text = element_markdown(size = 8, hjust = 0)) +
  force_panelsizes(rows = unit(6, 'cm'), cols = unit(6, 'cm'), respect = T) +
  labs(y = 'Number of contigs', x = 'Percentage of identity', subtitle = ani_df |> filter(str_detect(type, 'same')) |> pull(type) |> unique())

p_ani_hist_similar <- 
  ani_df |> 
  filter(str_detect(type, 'similar')) |> 
  ggplot(aes(x = pident)) +
  geom_histogram(binwidth = 1, color = 'white', linewidth = .2, boundary = 100) +
  facet_wrap(~ name, scales = 'free_y', ncol = 4) +
  theme_sags() +
  theme(strip.text = element_markdown(size = 8, hjust = 0))  +
  force_panelsizes(rows = unit(6, 'cm'), cols = unit(6, 'cm'), respect = T) +
  labs(y = 'Number of contigs', x = 'Percentage of identity', subtitle = ani_df |> filter(str_detect(type, 'similar')) |> pull(type) |> unique())

p_ani_hist_negative <- 
  wrap_plots(
    p_ani_hist_same,
    p_ani_hist_similar,
    nrow = 2
  ) +
  plot_annotation(tag_levels = list(c('**a**','**b**'))) &
  theme(plot.tag = element_markdown(),
        plot.subtitle = element_text(face = 'bold')) &
  scale_x_continuous(labels = ~ paste0(.x,'%'), limits = c(69,100)) &
  coord_cartesian(clip = 'off')

ggsave(plot = p_ani_hist_negative, filename = '../../figures/fig_ani_negative.pdf', height = 10.5, width = 14)
```

### Using length instead of number of contigs

```{r}
ani_length_df <- 
  ani_df |> 
  mutate(bin_pident = cut_width(pident, width = 1, boundary = 100)) |> 
  group_by(comparison, bin_pident, type, name) |> 
  summarise(bin_length = sum(len))

p_ani_hist_same_len <- 
  ani_length_df |> 
  filter(str_detect(type, 'same')) |> 
  ggplot(aes(x = bin_pident, y = bin_length/1e6)) +
  geom_col(color = 'white', linewidth = .2) +
  facet_wrap(~ name, scales = 'free_y', nrow = 1) +
  theme_sags() +
  theme(strip.text = element_markdown(size = 8, hjust = 0)) +
  force_panelsizes(rows = unit(6, 'cm'), cols = unit(6, 'cm'), respect = T) +
  labs(y = 'Size (Mbp)', x = 'Percentage of identity', subtitle = ani_df |> filter(str_detect(type, 'same')) |> pull(type) |> unique()) +
  scale_x_discrete(
    breaks = function(x) x[as.numeric(sub(".*,", "", gsub("\\(|\\]", "", x))) %in% c(70, 80, 90, 100)],
    labels = function(x) sub(".*,", "", gsub("\\(|\\]", "%", x)),
    drop = F
  )

p_ani_hist_similar_len <- 
  ani_length_df |> 
  filter(str_detect(type, 'similar')) |> 
  ggplot(aes(x = bin_pident, y = bin_length/1e6)) +
  geom_col(color = 'white', linewidth = .2) +
  facet_wrap(~ name, scales = 'free_y', ncol = 4) +
  theme_sags() +
  theme(strip.text = element_markdown(size = 8, hjust = 0)) +
  force_panelsizes(rows = unit(6, 'cm'), cols = unit(6, 'cm'), respect = T) +
  labs(y = 'Size (Mbp)', x = 'Percentage of identity', subtitle = ani_df |> filter(str_detect(type, 'similar')) |> pull(type) |> unique()) +
  scale_x_discrete(
    breaks = function(x) x[as.numeric(sub(".*,", "", gsub("\\(|\\]", "", x))) %in% c(70, 80, 90, 100)],
    labels = function(x) sub(".*,", "", gsub("\\(|\\]", "%", x)),
    drop = F
  )

p_ani_hist_negative_len <- 
  wrap_plots(
    p_ani_hist_same_len,
    p_ani_hist_similar_len,
    nrow = 2
  ) +
  plot_annotation(tag_levels = list(c('**a**','**b**'))) &
  theme(plot.tag = element_markdown(),
        plot.subtitle = element_text(face = 'bold')) &
  coord_cartesian(clip = 'off')

ggsave(plot = p_ani_hist_negative_len, filename = '../../figures/fig_ani_negative_len.pdf', height = 10.5, width = 14)
```

